api/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    # ================ My boards views ==================
    path('boards/owned/', owned_boards, name='owned_boards'),
    path('boards/shared/', shared_boards, name='shared_boards'),
    path('boards/<int:board_id>/', detail_board, name='detail_board'),
    path('boards/<int:board_id>/edit/', edit_board, name='detail_board'),

    # ================ Default boards CRUD views ==================
    path('boards/create/', create_board, name='create_board'),
    path('boards/<int:board_id>/delete/', delete_board, name='delete_board'),

    # ================ My lists views ==================
    path('boards/<int:board_id>/lists/', get_lists_by_board, name='get_lists_by_board'),
    path('boards/<int:board_id>/lists/create/', create_list, name='board_create_list'),
    path('boards/<int:board_id>/lists/<int:list_id>/edit/', edit_list, name='board_edit_list'),
    path('boards/<int:board_id>/lists/<int:list_id>/delete/', delete_list, name='board_delete_list'),

    # ================ Default lists CRUD views ==================
    path('lists/create/', create_list, name='create_list'),
    path('lists/<int:list_id>/delete/', delete_list, name='delete_list'),

    # ================ My tasks views ==================
    path('lists/<int:list_id>/tasks/', get_tasks_by_list, name='get_tasks_by_list'),
    path('boards/<int:board_id>/lists/<int:list_id>/tasks/create', create_task, name='create_task'),
    path('boards/<int:board_id>/lists/<int:list_id>/tasks/<int:task_id>/', get_task, name='get_task_from_board'),
    path('boards/<int:board_id>/lists/<int:list_id>/tasks/<int:task_id>/edit/', edit_task, name='edit_task_from_board'),
    path('boards/<int:board_id>/lists/<int:list_id>/tasks/<int:task_id>/delete/', delete_task, name='delete_task_from_board'),



    # ======================= task comments views ========================
    path('tasks/<int:task_id>/comments/', get_comments, name='get_comments_from_task'),
    path('tasks/<int:task_id>/comments/create', create_comment, name='create_comment'),
    path('tasks/<int:task_id>/comments/<int:comment_id>/like/', toggle_like_rest, name='create_comment'),

]

task_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('users/', include('user.urls')),
    path('api/', include('api.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import timedelta
from django.utils.timezone import now
import os

# Create your models here.

def avatar_upload_path(instance, filename):
    """
    Формирует путь для сохранения аватара, используя username пользователя.
    """
    ext = filename.split('.')[-1]  # Получаем расширение файла
    filename = f"{instance.user.username}.{ext}"  # Формируем новое имя файла
    return os.path.join('avatars/', filename)  # Путь для сохранения


class Profile(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name='profile',
        verbose_name='Пользователь'
    )
    avatar = models.ImageField(
        upload_to=avatar_upload_path,
        blank=True,
        null=True,
        verbose_name="Аватар"
    )
    bio = models.TextField(
        blank=True,
        null=True,
        verbose_name='О себе'
    )
    first_name = models.CharField(
        max_length=50,
        blank=True,
        null=True,
        verbose_name='Имя'
    )
    last_name = models.CharField(
        max_length=50,
        blank=True,
        null=True,
        verbose_name='Фамилия'
    )
    birth_date = models.DateField(
        blank=True,
        null=True,
        verbose_name='Дата рождения'
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата создания'
    )
    updated_at = models.DateTimeField(
        auto_now=True,
        verbose_name='Дата обновления'
    )

    class Meta:
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профили'

    def __str__(self):
        return self.user.username

    def save(self, *args, **kwargs):
        # Удаляем старый файл, если аватар изменился
        if self.pk:  # Проверяем, существует ли объект
            old_avatar = Profile.objects.filter(pk=self.pk).first().avatar
            if old_avatar and old_avatar.name != self.avatar.name:
                old_avatar_path = old_avatar.path
                if os.path.exists(old_avatar_path):
                    os.remove(old_avatar_path)
        super().save(*args, **kwargs)


class Subscription(models.Model):
    BASE = 'base'
    PREMIUM = 'premium'

    TIER_CHOICES = [
        (BASE, 'Базовый'),
        (PREMIUM, 'Премиум'),
    ]

    profile = models.OneToOneField(
        Profile,
        on_delete=models.CASCADE,
        related_name='subscription',
        verbose_name='Профиль пользователя'
    )
    tier = models.CharField(
        max_length=20,
        choices=TIER_CHOICES,
        default=BASE,
        verbose_name='Тип подписки'
    )
    expires_at = models.DateTimeField(
        null=True,
        blank=True,
        verbose_name='Дата истечения подписки'
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата создания подписки'
    )
    updated_at = models.DateTimeField(
        auto_now=True,
        verbose_name='Дата последнего обновления подписки'
    )

    class Meta:
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'

    def is_active(self):
        """
        Проверяет, активна ли подписка.
        """
        return self.tier == self.PREMIUM and (self.expires_at is None or self.expires_at > now())

    def upgrade_to_premium(self, duration_days=30):
        if self.subscription_type == 'base':
            self.subscription_type = 'premium'
            self.expires_at = now() + timedelta(days=duration_days)
        elif self.subscription_type == 'premium':
            if self.expires_at and self.expires_at > now():
                # Продление активной подписки: прибавляем к дате окончания
                self.expires_at += timedelta(days=duration_days)
            else:
                # Если подписка истекла, начинаем с текущей даты
                self.expires_at = now() + timedelta(days=duration_days)
        self.save()

    def reset_to_base(self):
        self.subscription_type = 'base'
        self.expires_at = None
        self.save()

    class Meta:
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'

    def __str__(self):
        return f'{self.profile.user.username} -> {self.tier}'

templates/app_base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="csrf-token" content="{{ csrf_token }}">
    <title>{% block title %}TaskIT{% endblock %}</title>
    <link rel="shortcut icon" href="{% static 'img/shortcut.png' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;700&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/vue@2.6.14/dist/vue.js"></script>
    {% block styles %}{% endblock styles %}
</head>
<body>
<!-- Шапка -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <!-- Кнопка боковой панели и логотип -->
        <div class="d-flex align-items-center">
            <button class="btn btn-dark mx-3" id="sidebarToggle" aria-label="Открыть меню">
                <span class="navbar-toggler-icon"></span>
            </button>
            <a class="navbar-brand" href="{% url 'main' %}">Task<span style="color: orange;">IT</span></a>
        </div>


        <!-- Юзернейм с аватаркой -->
        {% if user.is_authenticated %}
        <div class="dropdown mx-4">
            <a class="nav-link dropdown-toggle d-flex align-items-center" role="button"
               data-bs-toggle="dropdown">
                <img src="{% if user.profile.avatar %}{{ user.profile.avatar.url }}{% else %}{% static 'img/default_avatar.png' %}{% endif %}"
                     alt="Avatar"
                     class="avatar-img rounded-circle me-2"
                     width="40"
                     height="40">
                {{ user.username }}
            </a>
            <ul class="dropdown-menu dropdown-menu-end">
                <li><a class="dropdown-item" href="{% url 'profile_detail' user.profile.id %}">Профиль</a></li>
                <li><a class="dropdown-item" href="{% url 'boards' %}">Мои доски</a></li>
                <li>
                    <hr class="dropdown-divider">
                </li>
                <li><a class="dropdown-item" href="{% url 'logout' %}">Выход</a></li>
            </ul>
        </div>
        {% endif %}
    </div>
</nav>

<!-- Боковая панель -->
<div id="sidebar" class="bg-dark text-white p-3 position-fixed top-0 start-0 vh-100">
    <button class="btn btn-close btn-close-white ms-auto" id="sidebarClose"></button>
    <ul class="sidebar-menu list-unstyled mt-4">
        <li><p href="/tariff" class="text-decoration-none d-block py-2"><i class="bi bi-currency-exchange"></i> Текущий тариф: <span class="badge bg-light text-dark">{{ user.profile.subscription.get_tier_display }}</span></p></li>

        <li><a href="{% url 'main' %}" class="text-decoration-none d-block py-2"><i class="bi bi-house-door"></i> Страница приветствия</a></li>
        <li><a href="{% url 'main' %}#features" class="text-decoration-none d-block py-2"><i class="bi bi-lightbulb"></i> Возможности</a></li>
        <li><a href="{% url 'prices_detail' %}" class="text-decoration-none d-block py-2"><i class="bi bi-cash-stack"></i> Тарифы</a></li>
        <li><a href="{% url 'profile_detail' user.profile.id %}" class="text-decoration-none d-block py-2"><i class="bi bi-person"></i> Профиль</a></li>

        <li><a href="{% url 'boards' %}" class="text-decoration-none d-block py-2"><i class="bi bi-kanban"></i> Мои доски</a></li>
<!--        <li><a href="#" class="text-decoration-none d-block py-2"><i class="bi bi-people"></i> Коллеги</a></li>-->
<!--        <li><a href="#" class="text-decoration-none d-block py-2"><i class="bi bi-clock-history"></i> Последние изменения</a></li>-->
<!--        <li><a href="#" class="text-decoration-none d-block py-2"><i class="bi bi-chat-dots"></i> Чат</a></li>-->


    </ul>
</div>

<!-- Контент -->
<main class="pt-4">
    {% block content %}
    {% endblock content %}
</main>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
<script src="{% static 'js/app_base.js' %}"></script>
{% block script %}{% endblock script %}
</body>
</html>

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="csrf-token" content="{{ csrf_token }}">
    <title>{% block title %}TaskIT{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;700&family=Montserrat:wght@400;700&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block styles %}{% endblock styles %}
</head>
<body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark">
        <div class="container">
            <a class="navbar-brand" href="/">Task<span>IT</span></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="/">Главная</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#features">Особенности</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/about">О нас</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/pricing">Цены</a>
                    </li>
                    <li class="nav-item">
                        <a class="btn btn-primary" href="/signup">Регистрация</a>
                    </li>
                    <li class="nav-item">
                        <a class="btn btn-light" href="/login">Войти</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <!-- Main Content -->
    <main>
        {% block content %}
        {% endblock content %}
    </main>



    <!-- Footer -->
    <footer class="text-center">
        <div class="container">
            <p>&copy; 2024 TaskIT. Все права защищены.</p>
            <p><a href="mailto:support@TaskIT.com">support@TaskIT.com</a></p>
        </div>
    </footer>

    <!-- Scripts -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

templates/board_detail.html
{% extends 'app_base.html' %}
{% load static %}

{% block title %}Доска {{ board.name }}{% endblock %}

{% block styles %}
<link rel="stylesheet" href="{% static 'css/board_detail.css' %}">
{% endblock styles %}

{% block content %}
<section class="kanban-board py-5" id="app" data-board-id="{{ board_id }}" data-user-id="{{ user.profile.id }}" data-default-avatar="{% static 'img/default_avatar.png' %}">
    <div class="container-fluid px-5">
        <h1 class="text-center mb-2">[[ board.name ]]</h1>
         <!-- Контейнер для описания доски -->
        <div class="board-description-container text-center mb-2">
            <p class="board-description">[[ board.description ]]</p>
        </div>

        <!-- Колонки и задачи -->
        <div class="kanban-board-wrapper" v-if="lists.length > 0">
            <div v-for="list in lists" :key="list.id" class="kanban-column" :data-list-id="list.id">
                <div class="card">
                    <div class="card-header text-white d-flex justify-content-center align-items-center position-relative">
                        <h4 class="mb-0">[[ list.name ]]</h4>
                        <i v-if="isOwner && list.name.toLowerCase() !== 'архив'" class="list-edit bi bi-pencil edit-icon position-absolute" @click="openEditListPopup(list)"></i>
                    </div>
                    <div class="card-body">
                        <div v-if="tasks[list.id] && tasks[list.id].length > 0">
                            <div v-for="task in tasks[list.id]" :key="task.id" class="task-card card mb-3"
                                 :class="{
                                     'task-urgent': task.is_urgent === true,
                                     'task-overdue': task.is_overdue === true,
                                 }">
                                <div class="card-body">
                                    <div class="task-title-container d-flex gap-2 justify-content-between align-items-center">
                                        <i v-if="canMoveTask(task)" class="move-arrow bi bi-arrow-left-circle move-left" @click="moveTask(task.id, list.id, 'back')"></i>
                                        <h6 class="task-title mb-4">[[ task.title ]] <i v-if="canEditTask(task)" class=" task-edit bi bi-pencil edit-icon" @click="openEditTaskPopup(task)"></i></h6>
                                        <i v-if="canMoveTask(task)" class="move-arrow bi bi-arrow-right-circle move-right" @click="moveTask(task.id, list.id, 'forward')"></i>
                                    </div>
                                    <div class="d-flex justify-content-between align-items-center">
                                        <span class="task-deadline text-muted">Срок:<br>[[ task.due_date ]]</span>
                                        <div class="task-user">
                                            <a class="d-flex align-items-center" :href="baseUrl + '/users/profiles/' + task.assigned_to_id">
                                                <img :src="task.assigned_to_avatar || defaultAvatar"
                                                 alt="Avatar" class="avatar-img rounded-circle me-2" width="40" height="40">
                                            <span>[[ task.assigned_to_username ]]</span>
                                            </a>

                                        </div>
                                    </div>
                                </div>
                                <a class="btn btn-outline-primary w-100"
                                    :href="`lists/${task.status}/tasks/${task.id}/`">Детали
                                </a>
                            </div>
                        </div>
                        <p v-else class="text-center text-muted">Здесь ничего нет</p> <!-- Сообщение, если задач нет -->
                    </div>
                    <div class="card-footer p-0">
                        <button class="btn btn-primary w-100 h-100 rounded-0 rounded-bottom" @click="openAddTaskPopup(list.id)">Добавить задачу</button>
                    </div>
                </div>
            </div>

            <!-- Кнопка "Добавить список" -->
            <div v-if="isOwner" class="kanban-add-column d-flex align-items-start justify-content-start">
                <button class="btn btn-outline-primary" @click="openCreateListPopup">
                    <i class="bi bi-plus-circle"></i> Добавить список
                </button>
            </div>
        </div>

        <!-- Сообщение, если списков нет -->
        <div class="text-center" v-else>
            <p class="text-muted">Здесь ничего нет</p>
            <button v-if="isOwner"
                class="btn btn-outline-primary mt-3" @click="openCreateListPopup">
                <i class="bi bi-plus-circle"></i> Добавить список
            </button>
        </div>
    </div>

    <!-- Модальное окно для создания списка -->
    <div class="modal fade" id="addListModal" tabindex="-1" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Добавить список</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button>
                </div>
                <div class="modal-body">
                    <input
                        type="text"
                        v-model="newListName"
                        class="form-control"
                        placeholder="Введите название списка"
                    />
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
                    <button type="button" class="btn btn-primary" @click="addNewList">Добавить</button>
                </div>
            </div>
        </div>
    </div>

   <!-- Модальное окно для редактирования списка -->
    <div class="modal fade" id="editListModal" tabindex="-1" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Редактировать список</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button>
                </div>
                <div class="modal-body">
                    <input
                        type="text"
                        v-model="newListName"
                        class="form-control"
                        placeholder="Введите название списка"
                    />
                </div>
                <div class="modal-footer justify-content-between">
                    <button type="button" class="btn btn-danger" @click="deleteList">Удалить</button>
                    <div class="safe-btns">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
                        <button type="button" class="btn btn-primary" @click="editList">Сохранить</button>
                    </div>

                </div>
            </div>
        </div>
    </div>

    <!-- Модальное окно для создания задачи -->
    <div class="modal fade" id="addTaskModal" tabindex="-1" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Добавить задачу</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button>
                </div>
                <div class="modal-body">
                    <!-- Поле для названия задачи -->
                    <p class="mb-1">Название задачи:</p>
                    <input
                        type="text"
                        v-model="newTaskTitle"
                        class="form-control"
                        placeholder="Введите название задачи"
                    />
                    <br>

                    <p class="mb-1">Описание задачи:</p>
                    <!-- Поле для описания задачи -->
                    <textarea
                        v-model="newTaskDescription"
                        class="form-control"
                        rows="3"
                        placeholder="Введите описание задачи"
                    ></textarea>
                    <br>

                    <p class="mb-1">Дедлайн:</p>
                    <!-- Поле для выбора даты дедлайна -->
                    <input
                        type="date"
                        v-model="newTaskDeadline"
                        class="form-control"
                    />
                    <br>

                    <p class="mb-1">Ответственный:</p>
                    <!-- Поле для выбора ответственного -->
                    <select v-model="newTaskAssignedTo" class="form-control">
                        <option v-for="member in boardMembers" :key="member.id" :value="member.id">
                            [[ member.username ]]
                        </option>
                    </select>
                    <br>


                      <!-- Флажок для срочности -->
                    <div class="form-check">
                        <input type="checkbox" class="form-check-input" v-model="newTaskIsUrgent" id="urgentCheckbox" />
                        <label class="form-check-label" for="urgentCheckbox">Отметить как срочную</label>
                    </div>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
                    <button type="button" class="btn btn-primary" @click="addNewTask">Добавить</button>
                </div>
            </div>
        </div>
    </div>

    <!-- Модальное окно для редактирования задачи -->
    <div class="modal fade" id="editTaskModal" tabindex="-1" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Редактировать задачу</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button>
                </div>
                <div class="modal-body">
                    <p class="mb-1">Название задачи:</p>
                    <input
                        type="text"
                        v-model="newTaskTitle"
                        class="form-control"
                        placeholder="Введите название задачи"
                    />
                    <br>

                    <p class="mb-1">Описание задачи:</p>
                    <textarea
                        v-model="newTaskDescription"
                        class="form-control"
                        rows="3"
                        placeholder="Введите описание задачи"
                    ></textarea>
                    <br>

                    <p class="mb-1">Дедлайн:</p>
                    <input
                        type="date"
                        v-model="newTaskDeadline"
                        class="form-control"
                    />
                    <br>

                    <p class="mb-1">Ответственный:</p>
                    <select v-model="newTaskAssignedTo" class="form-control">
                        <option v-for="member in boardMembers" :key="member.id" :value="member.id">
                            [[ member.username ]]
                        </option>
                    </select>
                    <br>

                    <!-- Флажок для срочности -->
                    <div class="form-check">
                        <input type="checkbox" class="form-check-input" v-model="newTaskIsUrgent" id="urgentCheckbox" />
                        <label class="form-check-label" for="urgentCheckbox">Отметить как срочную</label>
                    </div>
                </div>
                <div class="modal-footer d-dlex justify-content-between">
                    <button type="button" class="btn btn-danger" @click="deleteTask">Удалить задачу</button>
                    <div class="safe-btns">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
                        <button type="button" class="btn btn-primary" @click="editTask">Сохранить</button>
                    </div>

                </div>
            </div>
        </div>
    </div>



</section>
{% endblock %}

{% block script %}
<script src="{% static 'js/board_detail.js' %}"></script>

{% endblock script %}

templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block styles %}<link rel="stylesheet" href="{% static 'css/login.css' %}">{% endblock styles %}

{% block title %}Вход в систему{% endblock %}

{% block content %}
<section class="login-section py-5">
    <div class="container-fluid d-flex justify-content-center align-items-center" style="min-height: 50vh;">
        <div class="col-md-4">
            <div class="card shadow-sm">
                <div class="card-header bg-primary text-white text-center">
                    <h4>Вход в систему</h4>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="username" class="form-label">Имя пользователя</label>
                            <input type="text" class="form-control" id="username" name="username" required>
                        </div>
                        <div class="mb-3">
                            <label for="password" class="form-label">Пароль</label>
                            <input type="password" class="form-control" id="password" name="password" required>
                        </div>
                        <button type="submit" class="btn btn-primary w-100">Войти</button>
                    </form>
                </div>
                <div class="card-footer text-center">
                    <p class="mb-0">Нет аккаунта? <a href="#">Зарегистрироваться</a></p>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/price_detail.html
{% extends "public_base.html" %}
{% load static %}

{% block title %}Тарифные планы{% endblock %}

{% block styles %}
<link rel="stylesheet" href="{% static 'css/price_detail.css' %}">
{% endblock %}

{% block content %}
<section class="pricing-section">
    <h1 class="pricing-title">Тарифные планы</h1>
    <div class="row justify-content-center">
        {% for tier, details in tiers.items %}
        <div class="col-md-3">
            <div class="pricing-card {% if details.is_highlighted %}highlighted{% endif %}">
                <div class="pricing-card-header">
                    {{ details.name }}
                    {% if details.is_highlighted %}
                        <p class="small text-white">Самый популярный</p>
                    {% endif %}
                </div>
                <div class="pricing-card-body">
                    <div class="price">
                        <span>{{ details.price }}₽ / месяц</span>
                        {% if details.old_price %}
                        <span class="old-price">{{ details.old_price }}₽</span>
                        {% endif %}
                    </div>
                    <ul class="features text-start">
                        {% for feature in details.features %}
                        <li><i class="bi bi-check2-circle"></i> {{ feature }}</li>
                        {% endfor %}
                        {% for disregard in details.disregards %}
                        <li class="text-muted"><i class="bi bi-dash-circle"></i> {{ disregard }}</li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="pricing-card-footer">
                    {% if tier == 'base' %}
                    <a href="{% url 'boards' %}" class="btn btn-primary">Начать использовать</a>
                    {% elif tier == 'premium' %}
                    {% if user.is_authenticated %}
                        <a href="{% url 'activate_premium' user.profile.id %}" class="btn btn-primary">Приобрести</a>
                    {% else %}
                        <a href="{% url 'login' %}" class="btn btn-primary">Приобрести</a>
                    {% endif %}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</section>
{% endblock %}